version: '3.4'

networks:
  local_auto_tier:
    driver: bridge


services:
    event_rules_storage_api:
        image: event_rules_storage_api:latest
        build:
            context: ./event_rules_storage_api/
            dockerfile: Dockerfile
        restart: always
        container_name: event_rules_storage_api
        environment:
          FLASK_DEBUG: 1
        ports:
            - 5000:5000
        depends_on:
            - db
        networks:
            - local_auto_tier

    db:
      image: postgres
      container_name: local_postgres_db
      restart: always
      environment:
        POSTGRES_DB: "testdb"
        POSTGRES_USER: "testadmin"
        POSTGRES_PASSWORD: "testtest"
        POSTGRES_HOST: "db"
      expose:
        - "5432"
      networks:
          - local_auto_tier

    # Mosquitto broker for mqtt protocol connection
    mosquitto:
      image: eclipse-mosquitto
      container_name: mosquitto
      expose:
        - "1883"
        - "9001"
      ports:
        - "1883:1883"
        - "9001:9001"
      network_mode: host
      # networks:
      #   - local_auto_tier

    communication_handler:
      image: communication_handler:latest
      network_mode: host
      build:
          context: ./communication_handler/
          dockerfile: Dockerfile
      restart: always
      container_name: communication_handler
      expose:
        - "8080"
      ports:
        - "8080:8080"
      env_file:
        - '.env-communication-handler'
      depends_on:
          - mosquitto
      # networks:
          # - local_auto_tier

