"""empty message

Revision ID: 2cdae4581d2d
Revises: a9b458969ff7
Create Date: 2020-08-12 10:21:10.164450

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2cdae4581d2d'
down_revision = 'a9b458969ff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controllers', sa.Column('graph', sa.JSON(), nullable=True))
    op.drop_column('controllers', 'graph_config')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controllers', sa.Column('graph_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('controllers', 'graph')
    # ### end Alembic commands ###
