"""empty message

Revision ID: 613ff824d366
Revises: 844689774c21
Create Date: 2020-08-07 11:57:28.743624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '613ff824d366'
down_revision = '844689774c21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controllers', sa.Column('configuration', sa.JSON(), nullable=True))
    op.drop_column('controllers', 'subscribers')
    op.drop_column('controllers', 'pins_configuration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controllers', sa.Column('pins_configuration', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('controllers', sa.Column('subscribers', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.drop_column('controllers', 'configuration')
    # ### end Alembic commands ###
