"""empty message

Revision ID: a9b458969ff7
Revises: 613ff824d366
Create Date: 2020-08-12 10:15:45.252097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9b458969ff7'
down_revision = '613ff824d366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controllers', sa.Column('esp_config', sa.JSON(), nullable=True))
    op.add_column('controllers', sa.Column('graph_config', sa.JSON(), nullable=True))
    op.drop_column('controllers', 'configuration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controllers', sa.Column('configuration', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('controllers', 'graph_config')
    op.drop_column('controllers', 'esp_config')
    # ### end Alembic commands ###
